.TH "BodyParts" 3 "Wed Aug 9 2017" "Version v0.7" "Segmented Fusion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BodyParts
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBodyParts\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBPI\fP = math\&.pi"
.br
.ti -1c
.RI "\fBRGBD\fP = imp\&.load_source('RGBD', '\&./lib/RGBD\&.py')"
.br
.ti -1c
.RI "\fBTrackManager\fP = imp\&.load_source('TrackManager', '\&./lib/tracking\&.py')"
.br
.ti -1c
.RI "\fBTSDFtk\fP = imp\&.load_source('TSDFtk', '\&./lib/TSDF\&.py')"
.br
.ti -1c
.RI "\fBGPU\fP = imp\&.load_source('GPUManager', '\&./lib/GPUManager\&.py')"
.br
.ti -1c
.RI "\fBMy_MC\fP = imp\&.load_source('My_MarchingCube', '\&./lib/My_MarchingCube\&.py')"
.br
.ti -1c
.RI "\fBStitcher\fP = imp\&.load_source('Stitcher', '\&./lib/Stitching\&.py')"
.br
.ti -1c
.RI "\fBGeneral\fP = imp\&.load_source('General', '\&./lib/General\&.py')"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
7 August 2017
@author: Inoe ANDRE
All process within a body part

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Segmented Fusion from the source code\&.
