.TH "dynamicFusion" 3 "Wed Aug 9 2017" "Version v0.7" "Segmented Fusion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dynamicFusion
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBvizualiazedata\fP ()"
.br
.ti -1c
.RI "def \fBmain\fP (GPUManager)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBGPU\fP = imp\&.load_source('GPUManager', '\&./lib/GPUManager\&.py')"
.br
.ti -1c
.RI "\fBGPUManager\fP = GPU\&.GPUManager()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Script to do segmented fusion
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "def dynamicFusion\&.main ( GPUManager)"

.PP
.nf
Create Menu to load data 
.fi
.PP
 
.SS "def dynamicFusion\&.vizualiazedata ()"

.PP
.nf
Vizualize the dataset NewData.mat which contains a moving body but the camera is fixed
Improve this
:return:

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Segmented Fusion from the source code\&.
