.TH "Menu" 3 "Wed Aug 9 2017" "Version v0.7" "Segmented Fusion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Menu
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMenu\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
File created by Diego Thomas the 21-11-2016

File to handle the menu main loop

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Segmented Fusion from the source code\&.
