.TH "Menu.Menu" 3 "Wed Aug 9 2017" "Version v0.7" "Segmented Fusion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Menu.Menu
.SH SYNOPSIS
.br
.PP
.PP
Inherits Frame\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBkey\fP (self, event)"
.br
.ti -1c
.RI "def \fBcallback\fP (self, event)"
.br
.ti -1c
.RI "def \fB__init__\fP (self, master=None)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfilename\fP"
.br
.ti -1c
.RI "\fBroot\fP"
.br
.ti -1c
.RI "\fBcanvas\fP"
.br
.ti -1c
.RI "\fBmenu\fP"
.br
.ti -1c
.RI "\fBmenu_label\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Class to handle menu GUI

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Segmented Fusion from the source code\&.
