.TH "RGBD" 3 "Wed Aug 9 2017" "Version v0.7" "Segmented Fusion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGBD
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRGBD\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsegm\fP = imp\&.load_source('segmentation', '\&./lib/segmentation\&.py')"
.br
.ti -1c
.RI "\fBGeneral\fP = imp\&.load_source('General', '\&./lib/General\&.py')"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
 File created by Diego Thomas the 16-11-2016
 improved by Inoe Andre from 02-2017

 Define functions to manipulate RGB-D data

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Segmented Fusion from the source code\&.
