.TH "dynamicFusion" 3 "Mon Aug 7 2017" "Version v0.5" "SegmentedFusion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dynamicFusion
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBvizualiazedata\fP ()"
.br
.ti -1c
.RI "def \fBmain\fP (GPUManager)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBGPU\fP = imp\&.load_source('GPUManager', '\&./lib/GPUManager\&.py')"
.br
.ti -1c
.RI "\fBGPUManager\fP = GPU\&.GPUManager()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Script to do dynamic fusion with topological changes.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "def dynamicFusion\&.main ( GPUManager)"

.PP
.nf
Create Menu to load data 
.fi
.PP
 
.PP
Definition at line 39 of file dynamicFusion\&.py\&.
.SS "def dynamicFusion\&.vizualiazedata ()"

.PP
.nf
Improve this
:return:

.fi
.PP
 
.PP
Definition at line 6 of file dynamicFusion\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SegmentedFusion from the source code\&.
