.TH "GPUManager.GPUManager" 3 "Mon Aug 7 2017" "Version v0.5" "SegmentedFusion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPUManager.GPUManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBprint_device_info\fP (self)"
.br
.ti -1c
.RI "def \fBload_kernels\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBplatform\fP"
.br
.ti -1c
.RI "\fBdevices\fP"
.br
.ti -1c
.RI "\fBcontext\fP"
.br
.ti -1c
.RI "\fBqueue\fP"
.br
.ti -1c
.RI "\fBprograms\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file GPUManager\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SegmentedFusion from the source code\&.
